"""Tg id

Revision ID: 23d4d7a97d13
Revises: f1e462a8e692
Create Date: 2025-01-07 19:23:20.618894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23d4d7a97d13'
down_revision: Union[str, None] = 'f1e462a8e692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tg_id', sa.BigInteger()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', '_is_admin',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('users', 'tg_id')
    op.alter_column('telegram_products', 'url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('products', 'target_audience',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('products', 'size',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.alter_column('products', 'image',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('products', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
