"""New structure of table

Revision ID: 40187f33f9d6
Revises: 3f68a673c5f3
Create Date: 2025-01-20 17:20:18.919074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40187f33f9d6'
down_revision: Union[str, None] = '3f68a673c5f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_products', sa.Column('brand', sa.String(), nullable=False))
    op.add_column('my_products', sa.Column('price_range', sa.String(), nullable=False))
    op.add_column('my_products', sa.Column('currency', sa.String(), nullable=False))
    op.add_column('my_products', sa.Column('channel_name', sa.String(), nullable=False))
    op.add_column('my_products', sa.Column('original_price', sa.String(), nullable=False))
    op.add_column('my_products', sa.Column('condition', sa.String(), nullable=False))
    op.add_column('my_products', sa.Column('category', sa.String(), nullable=False))
    op.add_column('my_products', sa.Column('delivery_options', sa.String(), nullable=False))
    op.add_column('my_products', sa.Column('url', sa.String(), nullable=False))
    op.add_column('my_products', sa.Column('payment_methods', sa.String(), nullable=False))
    op.add_column('my_products', sa.Column('discounted_price', sa.String(), nullable=False))
    op.add_column('my_products', sa.Column('discounted', sa.Boolean(), nullable=False))
    op.add_column('my_products', sa.Column('seller_contact', sa.String(), nullable=False))
    op.add_column('my_products', sa.Column('photo', sa.String(), nullable=False))
    op.alter_column('my_products', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               existing_server_default=sa.text("'No title'::text"))
    op.alter_column('my_products', 'size',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               existing_server_default=sa.text("'No size'::text"))
    op.alter_column('my_products', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               existing_server_default=sa.text("'No description'::text"))
    op.drop_column('my_products', 'source')
    op.drop_column('my_products', 'image')
    op.drop_column('my_products', 'state')
    op.drop_column('my_products', 'available')
    op.drop_column('my_products', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_products', sa.Column('price', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('my_products', sa.Column('available', sa.VARCHAR(length=50), server_default=sa.text("'Is available'::character varying"), autoincrement=False, nullable=True))
    op.add_column('my_products', sa.Column('state', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('my_products', sa.Column('image', sa.TEXT(), server_default=sa.text("'No image'::text"), autoincrement=False, nullable=True))
    op.add_column('my_products', sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.alter_column('my_products', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'No description'::text"))
    op.alter_column('my_products', 'size',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'No size'::text"))
    op.alter_column('my_products', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'No title'::text"))
    op.drop_column('my_products', 'photo')
    op.drop_column('my_products', 'seller_contact')
    op.drop_column('my_products', 'discounted')
    op.drop_column('my_products', 'discounted_price')
    op.drop_column('my_products', 'payment_methods')
    op.drop_column('my_products', 'url')
    op.drop_column('my_products', 'delivery_options')
    op.drop_column('my_products', 'category')
    op.drop_column('my_products', 'condition')
    op.drop_column('my_products', 'original_price')
    op.drop_column('my_products', 'channel_name')
    op.drop_column('my_products', 'currency')
    op.drop_column('my_products', 'price_range')
    op.drop_column('my_products', 'brand')
    # ### end Alembic commands ###
