"""I don't know

Revision ID: 3f68a673c5f3
Revises: 23d4d7a97d13
Create Date: 2025-01-11 21:59:43.953896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f68a673c5f3'
down_revision: Union[str, None] = '23d4d7a97d13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('title', sa.Text(), server_default='No title'),
    sa.Column('size', sa.Text(), server_default='No size'),
    sa.Column('description', sa.Text(), server_default='No description'),
    sa.Column('price', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('available', sa.String(length=50), server_default='Is available'),
    sa.PrimaryKeyConstraint('product_id', name='Unique my_product')
    )
    op.create_table('images',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['my_products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id', name='Unique image')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.drop_table('my_products')
    # ### end Alembic commands ###
