"""First migration

Revision ID: f1e462a8e692
Revises: 
Create Date: 2025-01-07 19:05:23.664918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1e462a8e692'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), default='No title'),
    sa.Column('image', sa.Text(), default='No image'),
    sa.Column('size', sa.String(length=40), default='No size'),
    sa.Column('description', sa.Text(), default='No description'),
    sa.Column('is_used', sa.String(length=50), nullable=False),
    sa.Column('target_audience', sa.Text()),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime()),
    sa.CheckConstraint('price >= 0', name='Good price'),
    sa.PrimaryKeyConstraint('id', 'type', name='Unique product')
    )
    op.create_table('telegram_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text()),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text()),
    sa.Column('username', sa.String(length=50)),
    sa.Column('password', sa.Text()),
    sa.Column('_is_admin', sa.Text()),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('telegram_products')
    op.drop_table('products')
    # ### end Alembic commands ###
